//ventas
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const AMOUNT_PRODUCTS = "AMOUNT_PRODUCTS";
export const SELECT_PROMOTORA = "SELECT_PROMOTORA";
export const RESET_STATE = "RESET_STATE";
export const SELECT_CLIENTE = "SELECT_CLIENTE";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const REST_QUANTITY = "REST_QUANTITY";
export const ADD_PRECIO_PROMOCION = "ADD_PRECIO_PROMOCION";
export const ADD_FECHA_VENTA = "ADD_FECHA_VENTA";
export const ADD_METODO_PAGO = "ADD_METODO_PAGO";
export const ADD_FACTURA = "ADD_FACTURA";
export const ADD_RECIBO_NOTA = "ADD_RECIBO_NOTA";
export const ADD_MONTO_EFECTIVO = "ADD_MONTO_EFECTIVO";
export const ADD_MONTO_TARJETA = "ADD_MONTO_TARJETA";
export const ADD_MONTO_DEPOSITO = "ADD_MONTO_DEPOSITO";
export const ADD_VENDEDOR = "ADD_VENDEDOR";

// cajas
export const SET_CAJA = "SET_CAJA";
export const ADD_TOTAL_EFECTIVO = "ADD_TOTAL_EFECTIVO";
export const ADD_TOTAL_TARJETA = "ADD_TOTAL_TARJETA";
export const ADD_TOTAL_BILLETES = "ADD_TOTAL_BILLETES";
export const ADD_TOTAL_MONEDAS = "ADD_TOTAL_MONEDAS";
export const ADD_BILLETES = "ADD_BILLETES";
export const ADD_MONEDAS = "ADD_MONEDAS";

// salida
export const SELECT_ALMACEN = "SELECT_ALMACEN";
export const SELECT_RETIRADO_POR = "SELECT_RETIRADO_POR";
export const SELECT_TOTAL = "SELECT_TOTAL";

// authentication
export const SELECT_USERNAME = "SELECT_USERNAME";
export const DESELECT_USERNAME = "DESELECT_USERNAME";
